//
//  GlobalConstants.h
//  Cyvasse
//
//  Created by John West on 1/4/14.
//  Copyright (c) 2014 John West. All rights reserved.
//

#ifndef Cyvasse_GlobalConstants_h
#define Cyvasse_GlobalConstants_h

#define LEFT_SIDE_X 0.0f
#define LEFT_SIDE_Y 0.0f
#define SCREEN_WIDTH 320.0f
#define BOARD_HEIGHT 320.0f
#define STATUS_BAR_HEIGHT 20.0f
#define TILE_SIZE 30.0f
#define FIRST_COLUMN_X 10.0f
#define FIRST_COLUMN_Y 30.0f
#define BOTTOM_BORDER_Y 330.0f

#define SELECT_TERRAIN_HEIGHT 100.0f
#define SELECT_TERRAIN_PICTURE_X1 20.0f
#define SELECT_TERRAIN_PICTURE_X2 130.0f
#define SELECT_TERRAIN_PICTURE_X3 240.0f
#define SELECT_TERRAIN_PICTURE_Y 20.0f
#define SELECT_TERRAIN_PICTURE_HEIGHT 60.0f
#define SELECT_TERRAIN_PICTURE_WIDTH 60.0f

#define STATISTICS_VIEW_HEIGHT 100.0f

#define STATISTICS_VIEW_PICTURE_X 100.0f
#define STATISTICS_VIEW_PICTURE_Y 100.0f
#define STATISTICS_VIEW_PICTURE_SIZE 100.0f

#define STATISTICS_VIEW_NAME_X 100.0f
#define STATISTICS_VIEW_NAME_Y 100.0f
#define STATISTICS_VIEW_NAME_HEIGHT 100.0f
#define STATISTICS_VIEW_NAME_WIDTH 100.0f

#define STATISTICS_VIEW_HEALTH_X 100.0f
#define STATISTICS_VIEW_HEALTH_Y 100.0f
#define STATISTICS_VIEW_HEALTH_HEIGHT 100.0f
#define STATISTICS_VIEW_HEALTH_WIDTH 100.0f

#define STATISTICS_VIEW_HEALTH_VALUE_X 100.0f
#define STATISTICS_VIEW_HEALTH_VALUE_Y 100.0f
#define STATISTICS_VIEW_HEALTH_VALUE_HEIGHT 100.0f
#define STATISTICS_VIEW_HEALTH_VALUE_WIDTH 100.0f

#define STATISTICS_VIEW_HEALTH_BAR_X 100.0f
#define STATISTICS_VIEW_HEALTH_BAR_Y 100.0f
#define STATISTICS_VIEW_HEALTH_BAR_HEIGHT 100.0f
#define STATISTICS_VIEW_HEALTH_BAR_WIDTH 100.0f

#define STATISTICS_VIEW_ATTACK_X 100.0f
#define STATISTICS_VIEW_ATTACK_X 100.0f
#define STATISTICS_VIEW_ATTACK_X 100.0f
#define STATISTICS_VIEW_ATTACK_X 100.0f

#define STATISTICS_VIEW_ATTACK_VALUE_X 100.0f
#define STATISTICS_VIEW_ATTACK_VALUE_X 100.0f
#define STATISTICS_VIEW_ATTACK_VALUE_X 100.0f
#define STATISTICS_VIEW_ATTACK_VALUE_X 100.0f

#define STATISTICS_VIEW_DEFENSE_X 100.0f
#define STATISTICS_VIEW_DEFENSE_X 100.0f
#define STATISTICS_VIEW_DEFENSE_X 100.0f
#define STATISTICS_VIEW_DEFENSE_X 100.0f

#define STATISTICS_VIEW_DEFENSE_VALUE_X 100.0f
#define STATISTICS_VIEW_DEFENSE_VALUE_X 100.0f
#define STATISTICS_VIEW_DEFENSE_VALUE_X 100.0f
#define STATISTICS_VIEW_DEFENSE_VALUE_X 100.0f

#define STATISTICS_VIEW_MOVEMENT_X 100.0f
#define STATISTICS_VIEW_MOVEMENT_X 100.0f
#define STATISTICS_VIEW_MOVEMENT_X 100.0f
#define STATISTICS_VIEW_MOVEMENT_X 100.0f



#endif
